---
version: '3.'
services:
  postgres-psql:
    container_name: postgres_psql
    image: postgres
    environment:
      POSTGRES_DB: psql
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      #- ./storage/postgresql:/var/lib/postgresql
      #- postgres-data:/var/lib/postgresql/data
      - ./postgres-psql:/data/postgres
      #- ./db/:/docker-entrypoint-initdb.d
      #- ./src/main/java/com/example/psql/resources/db/migrations/V00001__Create_country_table.sql
    #expose:
    #  - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always



  ## book-command-service Docker Compose Config
  psql_countries_api:
    container_name: psql_countries_api
    image: ivanzo/psql:latest
    #expose:
    #  - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-psql:5431/psql
    depends_on:
      - postgres-psql
    ports:
      - "8080:8080"
####
#volumes:
#  postgres-data:




